### ISSUE TITLE
Download File Transfer : SQLiteConstraintException

### ISSUE THREAD

**Issue by GoogleCodeExporter** [android-rcs/rcsjta#111]
```
Produced only 1 time.

The device receives an invitation to transfer a file via HTTP.

Upon insertion of the file transfer into the databae provider, an 
SQLiteConstraintException is thrown telling that "column ft_id is not unique".

Content of file transfer provider is not available (no root privilege).
Logcat trace is provided.

```

Original issue reported on code.google.com by `lemordan...@gmail.com` on 10 Jun 2015 at 3:10

Attachments:
* [SQLiteHttpFT_ConstraintException_column-ft_id_is_not_unique.txt](https://storage.googleapis.com/google-code-attachments/rcsjta/issue-111/comment-0/SQLiteHttpFT_ConstraintException_column-ft_id_is_not_unique.txt)

**Comment by yplo6403** [comment]
Never reproduced. No more applicable.
