### ISSUE TITLE
WiFi provisioning: unfriendly user interface

### ISSUE THREAD

**Issue by GoogleCodeExporter** [android-rcs/rcsjta#113]
```
When the device requires RCS provisioning via Wi-Fi, the user is prompted to 
enter its MSISDN in international format.

Some enhancements are possible to make the UI more friendly:
1- The UI is not localized
2- It should be possible to enter MSISDN in various formats (local or 
international)
3- If the user MSISDN is already persisted, dialog should be preset with it
4- Timer to enter the MSISDN is short (30s)
5- If phone number format is wrong, user should be notified and it should be 
possible to retry.


```

Original issue reported on code.google.com by `lemordan...@gmail.com` on 11 Jun 2015 at 4:59

**Comment by yplo6403** [comment]
When user clicks outside the MSISDN window, it cancels the alert dialog.
When user pastes the phone number, the paste popup is not visible (problem of theme).
![device-2015-08-20-184538](https://cloud.githubusercontent.com/assets/13114196/9389490/bd0724b4-476b-11e5-89df-a792cd8ab7e0.png)

**Comment by yplo6403** [comment]
See patch 460286c8693da675d3fd1da319970f0459a9aa98
- Prevent exit of activity if user clicks outside of the MSISDN dialog window.
- Use different theme to allow easy copy/paste operation in the MSISDN dialog window.
- Replace alert dialog by an error layout of the MSISDN activity.
