### ISSUE TITLE
Please switch development to gradle/Android Studio

### ISSUE THREAD

**Issue by uekemp** [android-rcs/rcsjta#128]
This is more of a feature request than an issue, but as Google has announced the [end of ADT support towards the end of 2015](http://android-developers.blogspot.de/2015/06/an-update-on-eclipse-android-developer.html), the project structure should be changed to support gradle and Android Studio as new build system.

**Comment by yplo6403** [comment]
The migration to Android studio and graddle is in the IceScrum backlog. Please see http://dev-ice.orange-labs.fr/icescrum/.

**Comment by yplo6403** [comment]
The migration to gradle and hence Android Studio has been performe (see integration branch)
