### ISSUE TITLE
RI: File Upload : no way to visualize thumbnail

### ISSUE THREAD

**Issue by marcbailly** [android-rcs/rcsjta#133]
when using the RI ti test File upload API, the user can select the tick to get a thumbnail. But at the end of the upload, the user car only visualize the file uploaded but not the thumbnail. It would be good to get another button "Show thumbnail".

**Comment by yplo6403** [comment]
Fixed with commit 073c3198fb8a3d718e681a73344aea815f37916d
Author: yplo6403 <philippe.lemordant@orange.com>
Date:   Fri Aug 21 11:09:27 2015 +0200

    RI: File Upload : no way to visualize thumbnail
    - allow user to download thumbnail from content server once transferred
