### ISSUE TITLE
MSISDN input dialog is not friendly when provisioning.

### ISSUE THREAD

**Issue by lgxace** [android-rcs/rcsjta#134]
What steps will reproduce the problem?
1.start a provisioning in wifi mode;
2.check the "RCS service" item in Settings apk;
3.then user will get a MSISDN input dialog.

What is the expected output? What do you see instead?
expected action:
    user should can paste the copied MSISDN to the edit box of the  dialog mentioned above.
actually:
    user can type the MSISDN to the edit box only.

What version of the product are you using? On what operating system?
product vision:3.1.1
OS:android 5.0.2

thanks a lot.

Please provide any additional information below.

for more,please refers to https://code.google.com/p/rcsjta/issues/detail?id=122

**Comment by yplo6403** [comment]
Issue #113 already solved.
Can you please retest with the lastest version (available at that link: https://github.com/android-rcs/rcsjta.build/tree/integration) since problem should have been fixed by patch ID 460286c8693da675d3fd1da319970f0459a9aa98 ?
See below:
    Issue 113: WiFi provisioning: unfriendly user interface
    - Prevent exit of activity if user clicks outside of the MSISDN dialog window.
    - Use different theme to allow easy copy/paste operation in the MSISDN dialog window.
    - Replace alert dialog by an error layout of the MSISDN activity.

**Comment by lgxace** [comment]
ok,I will feedback after tested it.
Thanks for you help!

**Comment by lgxace** [comment]
Hi,I have tested it and it works.
Thanks for you help again !

**Comment by yplo6403** [comment]
Thanks
