### ISSUE TITLE
[stack] API version number to be updated

### ISSUE THREAD

**Issue by marcbailly** [android-rcs/rcsjta#136]
When using the "about" of the Settings application, the API release mentioned is 'GSMA Blackbird 1.5" whereas it should be GSMA Blackbird 1.5.1.
(note: this is already OK in the About the RI application).

**Comment by yplo6403** [comment]
A fix has been pushed into integration branch. See:

>commit a791b3d5b6a7b308840bc270bfb41db2a9367691
>Author: yplo6403 <philippe.lemordant@orange.com>
>Date:   Thu Sep 10 14:18:41 2015 +0200

 >   Fix issue 136: API version number to be updated
 >   Core control: add the incremental number to the API version in the about window
