### ISSUE TITLE
App names

### ISSUE THREAD

**Issue by ErdemErsoz** [android-rcs/rcsjta#137]
It would be better to rename Provisioning app to RCS Provisioning and Settings app to RCS Settings. So that they (also RCS RI app) will be listed together in the app list and the users will not miss them.

**Comment by yplo6403** [comment]
A fix has been pushed. See:
>commit 57c30b27509b9b6abd02cdd6e82b650d3cae36d6
>Author: yplo6403 <philippe.lemordant@orange.com>
>Date:   Thu Sep 10 17:57:29 2015 +0200

>    Fixes  Issue 137 App names
>    - Prefixes launched activity name by 'RCS' for consistency and to facilitate listing/filtering of RCS apps.
>    - Gives the same name to launched activity and apps (when relevant).
>    - Gives the same name to apps and APK (when relevant).

Please download the latest SDK to check if it is what you expect.
