### ISSUE TITLE
RI: File Transfer service configuration: RI stopped when clicking on AA enabled

### ISSUE THREAD

**Issue by marcbailly** [android-rcs/rcsjta#150]
On the file transfer configuration screen, when clicking either on the "AA enabled" or on the "AA enabled in roaming", the RI application systematically stops.

**Comment by yplo6403** [comment]
Please provide more information: logcat trace and if usefull also wireshark trace.

**Comment by yplo6403** [comment]
[log-AA.txt](https://github.com/android-rcs/rcsjta/files/7721/log-AA.txt)

**Comment by yplo6403** [comment]
Fixed by commit:
commit 6b144957e630c843ad24e2aed224c2e18698b561
Author: unknown <yplo6403@EB-OR1022204.rd.francetelecom.fr>
Date:   Tue Oct 6 09:28:10 2015 +0200

    Fixes issue 150: RI: File Transfer service configuration: RI stopped when clicking on AA enabled
    - RI: consider AutoAcceptFileTransferChangeable parameter value to enable or not the AA settings
    - RI: do not allow change of AutoAcceptFileTransferInRoaming if AutoAcceptFileTransfer is not enabled in normal conditions
    - Core provisioning: add AutoAcceptFileTransferInRoaming and AutoAcceptFileTransferChangeable settings to local provisioning
