### ISSUE TITLE
Unecessary convertions of ChatMessage

### ISSUE THREAD

**Issue by yplo6403** [android-rcs/rcsjta#152]
Upon sending geoloc message, content is converted into its network representation then saved it to its API representation in the provider. After dequeuing we again convert it to its network representation and finally we send it. This multiple conversions are useless.
Only necessary convertions of Chat message to network represenation in the last step when you need it to send it on the network should be done.
Internally, the stack should only use API representation.

**Comment by MurthyVadapalli** [comment]
Hi,

Implementation for this issue has been done now , and i have made a pull request for same .

Sha  reference : 00bfbe45e159148c96298f34f28730ba24c0c6d4

**Comment by MurthyVadapalli** [comment]
Changes are now been merged through commit : 9767970cfb20fc2d5809f1e910a21d20f9562597
