### ISSUE TITLE
No IP (video) calling in RI app

### ISSUE THREAD

**Issue by icarapovic** [android-rcs/rcsjta#154]
In the stack/core, there is support for IP calls, and IP video calls, as those fields can be enabled. But in the reference app, there is no support for making IP video calls. When I try using video share, it requires to place a normal GSM call before that. The core has some references as "ipcalldraft".

Will IP (video) calling be supported in the RI app? Is the IP video calling even stable and usable inside the stack?

**Comment by yplo6403** [comment]
No the IP calling has been removed from the scope of the TAPI 1.5.1 (master and tapi_1.5.1 branches).
Legacy IP calling code has been fully removed from the core stack and the RI as well.

**Comment by icarapovic** [comment]
If its not a problem, could you provide any info will it be in development anywhere else or is there a place where I can get more info on IP calling using RCS?
