### ISSUE TITLE
The value of parameter "terminal_sw_version" ?

### ISSUE THREAD

**Issue by lgxace** [android-rcs/rcsjta#157]
RCS device must provide a value of parameter "terminal_sw_version" in http request when provisioning.

However,which a appropriate value we should provide to the parameter "terminal_sw_version"? android version or any others ?

any help for me ?

BR
thanks.

**Comment by lgxace** [comment]
and how to get the value ?

**Comment by icarapovic** [comment]
I think it's the OS version, terminal_sw_version=5.1.1

**Comment by yplo6403** [comment]
See com.gsma.rcs.core.TerminalInfo#getTerminalSoftwareVersion
it is set to the os.android.Build.DISPLAY.

**Comment by lgxace** [comment]
@yplo6403 ok,thanks !
