### ISSUE TITLE
[RI] Image sharing Invitation discarded on receiver side if previous activity is not closed

### ISSUE THREAD

**Issue by marcbailly** [android-rcs/rcsjta#161]

**Comment by yplo6403** [comment]
Issue fixed by commit:
commit 7f12a4bd8eb20a04d7b09ac01e38e9d855333ec0
Author: Philippe LEMORDANT <philippe.lemordant@orange.com>
Date:   Wed Oct 14 17:41:58 2015 +0200

    Fixes Issue 161 : [RI] Image sharing Invitation discarded on receiver side if previous activity is not closed
    - process onNewIntent for ReceiveImageSharing and ReceiveGeolocSharing activities
    - correct a typo on the package name for the UndeliveredFileReceiver
