### ISSUE TITLE
Double STARTED event broadcasted in group chat scenarios

### ISSUE THREAD

**Issue by oflisback** [android-rcs/rcsjta#165]
Refactoring GroupChatLog.setRejoinId to remove setting chat state as side-effect. This separation was necessary since we only want to set and broadcast STARTED in case the group chat isn't already STARTED.

This change was integrated through: https://github.com/android-rcs/rcsjta/commit/b35f5eab83e1e12e452f1fca51f1aba55fa1f8db

![gc_double_started](https://cloud.githubusercontent.com/assets/12221141/10507440/b74d4a54-7320-11e5-86ac-f610965e4c9b.png)

**Comment by yplo6403** [comment]
Issue fixed by commit:
commit 0eabefd6255f18928edae8737024dffb8141f343
Author: Ola Flisbäck <ola.flisback@sonymobile.com>
Date:   Thu Oct 8 15:28:59 2015 +0200

    Fix for double STARTED broadcasts

    Refactoring GroupChatLog.setRejoinId to remove setting chat state
    as side-effect. This separation was necessary since we only want
    to set and broadcast STARTED in case the group chat isn't already
    STARTED.
