### ISSUE TITLE
Bad criteria to dequeue a HTTP file transfer upload

### ISSUE THREAD

**Issue by yplo6403** [android-rcs/rcsjta#166]
__Initial conditions:__ a HTTP file transfer is initiated from A to B
__Actions:__ After all bytes have been transferred and before A reads the POST response containing the downloadURI, shutdown the A device.
__Result:__  The FileTransferData.KEY_DOWNLOAD_URI is null in the filetransfer provider.
__Action:__ Restart the A device.
__Expected result:__ The file transfer should be marked as failed (or resumed from start).
__Result:__ The A device tries to send the invitation to download to B. As the download URI is null, a null pointer exception is thrown. See attached trace.
[NPE_WhileDequeuinghttpFileTransferUpload.txt](https://github.com/android-rcs/rcsjta/files/13835/NPE_WhileDequeuinghttpFileTransferUpload.txt)
![capture](https://cloud.githubusercontent.com/assets/13114196/10508074/1fb69c90-7325-11e5-8cef-8fde977805a9.PNG)

**Comment by MurthyVadapalli** [comment]
Fix in place , I will share the patch to Philippe for review tomorrow.

**Comment by yplo6403** [comment]
Issue fixed with commit:
commit 50b06342ff1b8a5738558555032062464950ca17
Author: yplo6403 <philippe.lemordant@orange.com>
Date:   Tue Nov 3 09:25:50 2015 +0100

    Fixes issue 166: Bad criteria to dequeue a HTTP file transfer upload

    - Checks that download URI is not null when trying to dequeue file transfer
    - Checks that direction is outgoing when trying to dequeue file transfer
    - Saves download URI as soon as it is known in order to allow dequeuing in background
    - File transfer invitation is always queued (and not sent directly from the HttpFileTransferSession).
      HttpFileTransferSession only encompasses the HTTP media.
    - Catch multiple exception types (JDK 1.7) when block is identical
    - No parameterized type of the constructor for generic instance (JDK 1.7)
    - Use of Override statement to replace redundant comments
