### ISSUE TITLE
Undelivered file transfer is not working properly

### ISSUE THREAD

**Issue by yplo6403** [android-rcs/rcsjta#168]
As per specification, undelivered timers are applicable only for HTTP based file transfers (and only single file transfers).
An undelivered timer is started after the file upload is successful and the file information is sent in a chat message. if a delivery notification is not received before the expiration of this timer, an intent is broadcasted to client apps.
In the attached trace we can see that the undelivered message is triggered on the terminating side (it should be triggered on the originating side).
[UndeliveredHttpOneToOneFileTransfer.txt](https://github.com/android-rcs/rcsjta/files/14805/UndeliveredHttpOneToOneFileTransfer.txt)

**Comment by MurthyVadapalli** [comment]
Fix in place , I will share the patch to Philippe for review tomorrow.

**Comment by yplo6403** [comment]
Bug fixed with commit:
commit d96462949d6075ef1755f9da499481804a4692a3
Author: Kristoffer Karlsson <kristoffer.karlsson01@gmail.com>
Date:   Fri Oct 23 09:16:55 2015 +0200

    Only schedule delivery expiration for outgoing FT
