### ISSUE TITLE
[Stack / RI] File Transfer provisionning

### ISSUE THREAD

**Issue by marcbailly** [android-rcs/rcsjta#172]
In the RCS provisionning app (tab "Profile"), even if the "File Transfer" option is unticked, the RI displays the File transfer as activated in the Capabilities / My capabilities screen.  (while this is not the case for the other services).

**Comment by yplo6403** [comment]
Fixed with commit:
commit fc74da2de5aff2b510106ef07de5079a96447f37
Author: yplo6403 <lemordant.philippe@gmail.com>
Date:   Thu Oct 29 09:35:23 2015 +0100

    Fixes Issue 172: [Stack / RI] File Transfer provisionning

    The local provisioning was not exposing the File Transfer HTTP capacity.
