### ISSUE TITLE
NPE while logging run time exception in HTTP download

### ISSUE THREAD

**Issue by yplo6403** [android-rcs/rcsjta#173]
[NPE_runtimeException.txt](https://github.com/android-rcs/rcsjta/files/16822/NPE_runtimeException.txt)
After several pause/resume duringHTTP file download, the transfer failed due to a runtime exception but another NPE occurred while logging the exception because the mRemoteInstanceId is null. 
The logging of root cause is hidden by the last NPE.
During exception handling, we should take car not to generate another exception.

**Comment by yplo6403** [comment]
I think I reproduced the bug (after having removed the concatenation which throws the NPE) and then got the initial cause (to be fixed in a separate issue/patch).
[RootCauseHttpDownload.txt](https://github.com/android-rcs/rcsjta/files/16835/RootCauseHttpDownload.txt)

**Comment by MurthyVadapalli** [comment]
Hi , 

The null pointer occur because we use concat  (may be we should not use it and instead use stringbuilder as it can still print the log , without causing NULL pointer). I will change this.

Regarding RootCauseHttpDownload.txt , we need to check but yes we should take this as a new issue.

Regards
Murthy

**Comment by yplo6403** [comment]
I fully agree.

**Comment by yplo6403** [comment]
Fixed with commit:
commit a9ce63c36d82e8a14ab6f058406df288a79d517b
Author: Vadapalli Murthy <vadapalli.murthy@sonymobile.com>
Date:   Mon Oct 26 18:38:26 2015 +0100

    Replaced String concat with StringBuilder append

    While logging for exceptions in some places we
    used .concat to append different id's so that we
    can make the exception message more intutive for
    debugging purposes, However in some cases these
    id's are NULL and hence .concat ends up in
    throwing Null-Pointer.
    As it's not good that a exception message inturn
    throws another exception as in such cases the
    original trace is lost, Made changes in all such
    places to use StringBuilder.append instead.

    Changes are done only for the cases related to
    Exception Handling.

    Change-Id: I81f7a210fd7ce3d4651cf3b1cf18485d66318727
