### ISSUE TITLE
Video Sharing failed-Bad RTCP packet format when Video Sharing

### ISSUE THREAD

**Issue by lgxace** [android-rcs/rcsjta#177]
When Video share with other OEM RCS, our RCS-core received some other new RTCP packet tpye(e.g. value 206),then RCS stack throw "Bad RTCP packet format" exception.

class full path:
rcsjta/mediaplayer/src/com/orangelabs/rcs/core/ims/protocol/rtp/core/RtcpPacketReceiver.java or
rcsjta/core/src/com/gsma/rcs/core/ims/protocol/rtp/core/RtcpPacketReceiver.java

Exception position:
RtcpPacketReceiver.java->private RtcpPacket parseRtcpPacket(Packet packet)-> switch (type) {}-> default:
                    mStats.numUnknownTypes++;
                    throw new IOException("Bad RTCP packet format");

the android version is 5.0.1

**Comment by lgxace** [comment]
any help to me ?

**Comment by lgxace** [comment]
emergent issue, any help for me ?

Thanks & Regards,

**Comment by jmauffret** [comment]
The RTCP packet type of value 206 doesn't exist in the RFC3550. So it is not supported in the stack.
