### ISSUE TITLE
Secondary provisioning server invalid if you accidentally add space or newline

### ISSUE THREAD

**Issue by stk3** [android-rcs/rcsjta#178]
I easily happens that you add a space due to autocompletion in the RCS provisioning app or a new line due to pressing enter. Then provisioning does not work. It can be hard for new users to understand why, and how to solve it. The solution I think would be that the string is trimmed before it is saved.

**Comment by yplo6403** [comment]
Issue fixed by commit Id 47e3b80c8b7c00840d838e92cebbdc20f3926a23
Let us know if it really meets your initial requirement in order to close the issue.

**Comment by stk3** [comment]
Yes it does meet my intial requirements.
