### ISSUE TITLE
Creating a new SIP request in an existing dialog will copy superflous SIP headers from the last response received

### ISSUE THREAD

**Issue by SchmitzA** [android-rcs/rcsjta#181]
A BYE request which is sent in an existing dialog may contain headers like "warning" or "supports" received from a previous 200OK. Same goes for a RE-INVITE (for session refresh); this may also contain some strange SIP headers copied unnecessarily.

**Comment by yplo6403** [comment]
Please submit your patch.

**Comment by yplo6403** [comment]
Bug fixed by aligning with NIST version 1.2 
commit ID 2a5406ec02bc0499634f42d4d0365c743fda88e2
