### ISSUE TITLE
When transferring a file, both file itself and thumbnail are displayed in the album

### ISSUE THREAD

**Issue by MurthyVadapalli** [android-rcs/rcsjta#185]
1. Initiate chat session between users A and B
2. Send a file from A to B (http) using already established chat session
Expected: Only file itself is displayed in the album
Actual: Both file itself and thumbnail are displayed in album

**Comment by MurthyVadapalli** [comment]
Possible solution : 
File icons are shown in the album since the media scanner
finds them and categorises them as images.
The file icons are now placed in a new folder "rcs/fileicons/"
with a file named ".nomedia" so that the media scanner will
not scan the file icons folder and will not create preview
images in photo viewer app. This new folder is created if not
already existing at all times when the RCS core service is started.

The patch will be submit for review.

**Comment by yplo6403** [comment]
Bug fixed with commit:
commit b00abd58fecf7bfd7e7a46619c0550a2cefef2b5
Author: Stefan Karlsson <stefan3.karlsson@sonymobile.com>
Date:   Fri Dec 18 10:52:08 2015 +0100

    File icons hidden in a marked folder

    File icons are shown in the album since the media scanner
    finds them and categorises them as images.
    The file icons are now placed in a new folder "rcs/fileicons/"
    with a file named ".nomedia" so that the media scanner will
    not scan the file icons folder and will not create preview
    images in photo viewer app. This new folder is created if not
    already existing at all times when the RCS core service is started.

    Issue#185
