### ISSUE TITLE
Multiple bandwidth parameter in SDP on session level not supported 

### ISSUE THREAD

**Issue by SchmitzA** [android-rcs/rcsjta#198]
If there's more than one bandwidth parameter b on session level the whole SDP parsing fails.

The following real live SDP (although valid) could not be parsed for example:
v=0
o=DELETED* 12345660 0 IN IP4 193.159.154.13
s=SS IMS
c=IN IP4 193.159.154.16
b=AS:440
b=RS:5500
b=RR:16500
t=0 0
m=video 19568 RTP/AVP 117 115
b=AS:440
b=RS:5500
b=RR:16500
a=rtpmap:117 H264/90000
a=framerate:20
a=framesize:117 320-240
a=fmtp:117 profile-level-id=42800C;packetization-mode=1;sprop-parameter-sets=Z0KADNoFB+gG0KE1,aM4BnyA=
a=rtpmap:115 H264/90000
a=framesize:115 176-144
a=fmtp:115 profile-level-id=42900B;packetization-mode=1;sprop-parameter-sets=Z0KQC+kFicg=,aM4BnyA=
a=extmap:7 urn:3gpp:video-orientation
a=sendonly

*client deleted for privacy reasons

**Comment by yplo6403** [comment]
Bug fixed with commit ID 862d2eedba909d639f4c735a1182b909a2bfe696
