### ISSUE TITLE
Wrong constraint set byte set in H264 RTP stream 

### ISSUE THREAD

**Issue by SchmitzA** [android-rcs/rcsjta#199]
NativeH264EncoderParams defines profile_iop as Byte in NativeH264EncoderParams#setProfilesAndLevel. If highest bit should be set (like in 0x80 for baseline profile 1.2 0x42800C) the check <0 in line 333 prevents that. So 0x42800C announced in SDP becomes 0x42000C in RTP.

**Comment by yplo6403** [comment]
Can you please provide a patch for this ?

**Comment by yplo6403** [comment]
Fixed with commit 4e979f450ff7b3722c6a02d401ac0be2e40a1513
