### ISSUE TITLE
Core: do not insert +g.oma.sip-im tag into capabilities options

### ISSUE THREAD

**Issue by yplo6403** [android-rcs/rcsjta#212]
According to RCS 5.3 section 2.6.1.1.2:

_"+g.oma.sip-im" feature tag is used at SIP Registration and in SIP transactions but not used to identify a service capability._
    
The "+g.oma.sip-im" tag should be removed from the capabilities options.

See below Option resquest with bad feature tag in Accept-Contact header:

`OPTIONS tel:+33642575779 SIP/2.0
Call-ID: X1sQhRVsAA@10.29.4.251
CSeq: 1 OPTIONS
From: <tel:+33640519308>;tag=X1sQhRVtAA
To: <tel:+33642575779>
Via: SIP/2.0/UDP 10.29.4.251:6832;branch=z9hG4bKdd3cd2e69c4e0435ab41a9b240d82075373037;rport
Max-Forwards: 70
Contact: <sip:10.29.4.251:6832;transport=UDP>;+sip.instance="<urn:gsma:imei:35824005-944763-1>";+g.oma.sip-im;+g.3gpp.iari-ref="urn%3Aurn-7%3A3gpp-application.ims.iari.rcse.im,urn%3Aurn-7%3A3gpp-application.ims.iari.rcse.ft,urn%3Aurn-7%3A3gpp-application.ims.iari.rcs.fthttp,urn%3Aurn-7%3A3gpp-application.ims.iari.rcs.ftthumb,urn%3Aurn-7%3A3gpp-application.ims.iari.rcs.ext.streaming,urn%3Aurn-7%3A3gpp-application.ims.iari.rcs.ext.messaging";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.gsma.rcs.extension"
Accept: application/sdp
Accept-Contact: *;+g.oma.sip-im;+g.3gpp.iari-ref="urn%3Aurn-7%3A3gpp-application.ims.iari.rcse.im,urn%3Aurn-7%3A3gpp-application.ims.iari.rcse.ft,urn%3Aurn-7%3A3gpp-application.ims.iari.rcs.fthttp,urn%3Aurn-7%3A3gpp-application.ims.iari.rcs.ftthumb,urn%3Aurn-7%3A3gpp-application.ims.iari.rcs.ext.streaming,urn%3Aurn-7%3A3gpp-application.ims.iari.rcs.ext.messaging";+g.3gpp.icsi-ref="urn%3Aurn-7%3A3gpp-service.ims.icsi.gsma.rcs.extension"
Allow: INVITE,UPDATE,ACK,CANCEL,BYE,NOTIFY,OPTIONS,MESSAGE,REFER
Route: <sip:193.253.72.118:5060;transport=udp;lr>
P-Preferred-Identity: <tel:+33640519308>
User-Agent: ExttoExt-client/Ext1.0 IM-client/OMA1.0 LGE/hammerhead-KTU84M LGE/RCSAndr-2.0
Content-Length: 0`

**Comment by MurthyVadapalli** [comment]
+1 for the changes
