### ISSUE TITLE
FT XML info document handling is filtering new lines

### ISSUE THREAD

**Issue by SchmitzA** [android-rcs/rcsjta#220]
HttpUploadManager#convertStreamToString is filtering out any new line character like 0x0a which may be needed later on for parsing as white space to seperate parameters within an element.
E.g. the current implementation of the above method is transforming the valid sequence
<file xmlns="urn:gsma:params:xml:ns:rcs:rcs:fthttp"\n
xmlns:e="urn:gsma:params:xml:ns:rcs:rcs:up:fthttpext">
into an invalid sequence
<file xmlns="urn:gsma:params:xml:ns:rcs:rcs:fthttp"xmlns:e="urn:gsma:params:xml:ns:rcs:rcs:up:fthttpext">
So line 484 of HttpUploadManager#convertStreamToString should be changed from
sb.append(line);
to
sb.append(line).append('\n');

**Comment by yplo6403** [comment]
OK fix pushed on all branches (integration, master, tapi_1.6.1 and tapi_1.5.1).
Thanks
