### ISSUE TITLE
Timer mechanism not suitable for Android

### ISSUE THREAD

**Issue by GoogleCodeExporter** [android-rcs/rcsjta#78]
```
The NIST SIP stack part makes use of Java Timer and its schedule method. 
Unfortunately, timers in Android may not be executed on time if device is 
sleeping.
I think we do have three options:
a) change from Timer to AlarmManager which would result in a massiv 
reconstruction
b) set wakelocks for the time any recuring timer is active which may drain the 
battery
c) mitigate the impact for a recurring timer by checking with every tick 
whether the overarching timer is still valid or already exceeded. In the later 
case: fire the timeout event "immediately" and forget about the remaining ticks.
```

Original issue reported on code.google.com by `andreas-...@telekom.de` on 18 Nov 2014 at 1:00

**Comment by yplo6403** [comment]
Commit merged into integration
$ git cat-file -p 7861d880ef1f26a51857d148a1e8b298da87fc75
tree b7e6603b5277295a30037e33b0c0cd15718b1d73
parent d740789c34d3fb60498d22b333f85594156e615e
author Andreas Schmitz <andreas-schmitz@telekom.de> 1416475101 +0100
committer Andreas Schmitz <andreas-schmitz@telekom.de> 1416475101 +0100

issue#78 Timer mechanism not suitable for Android
