### ISSUE TITLE
RI: bad error code displayed when we close the session

### ISSUE THREAD

**Issue by GoogleCodeExporter** [android-rcs/rcsjta#97]
```
The error code is "REJECTED_BY_REMOTE". This should be "TERMINATED_BY_REMOTE".



```

Original issue reported on code.google.com by `jmauffret@gmail.com` on 4 Mar 2015 at 7:26

**Comment by yplo6403** [comment]
This is REJECTED_BY_REMOTE if rejected by remote or ABORTED_BY_REMOTE is remote aborted the session.
